packages:
  - "apps/*"
  - "docs"

catalog:
  "@inlang/paraglide-js": ^2.16.0
  "@inlang/plugin-message-format": ^4.4.0
  "@schedule-x/calendar": ^4.4.0
  "@schedule-x/calendar-controls": ^4.4.0
  "@schedule-x/current-time": ^4.4.0
  "@schedule-x/date-picker": 4.4.0
  "@schedule-x/event-modal": ^4.4.0
  "@schedule-x/event-recurrence": ^4.4.0
  "@schedule-x/events-service": ^4.4.0
  "@schedule-x/ical": ^4.4.0
  "@schedule-x/theme-default": ^4.4.0
  "@schedule-x/theme-shadcn": ^4.4.0
  "@schedule-x/vue": ^4.1.0
  "@types/node": ^24
  better-all: ^0.0.7
  dotenv: ^17
  drizzle-kit: 1.0.0-beta.20
  drizzle-orm: 1.0.0-beta.20
  hono: ^4
  lru-cache: ^11.3.3
  npm-run-all2: ^8
  oxc-minify: ^0.124.0
  oxfmt: ^0.44.0
  oxlint: ^1.59.0
  temporal-polyfill: 0.3.0
  tsdown: ^0.20.3
  tsx: ^4.21.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitepress: 2.0.0-alpha.17
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  wrangler: ^4

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
