packages:
  - "apps/*"
  - "docs"

catalog:
  "@types/node": ^24
  dotenv: ^17
  drizzle-kit: 1.0.0-beta.20
  drizzle-orm: 1.0.0-beta.20
  hono: ^4
  npm-run-all2: ^8
  oxc-minify: ^0.124.0
  oxfmt: ^0.44.0
  oxlint: ^1.59.0
  tsdown: ^0.20.3
  tsx: ^4.21.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitepress: 2.0.0-alpha.17
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  wrangler: ^4

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
