packages:
  - apps/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  dotenv: ^17
  hono: ^4
  npm-run-all2: ^8
  oxfmt: ^0.44.0
  oxlint: ^1.59.0
  tsdown: ^0.20.3
  tsx: ^4.21.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  wrangler: ^4

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
