services:
  bot:
    image: ghcr.io/remoodle/remoodle:latest
    restart: unless-stopped
    environment:
      SERVICE_NAME: bot
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      HATCHET_CLIENT_TOKEN: ${HATCHET_CLIENT_TOKEN}
      HATCHET_CLIENT_TLS_STRATEGY: none
      DATABASE_URL: /data/remoodle.db
    volumes:
      - data:/data

  worker:
    image: ghcr.io/remoodle/remoodle:latest
    restart: unless-stopped
    environment:
      SERVICE_NAME: worker
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      HATCHET_CLIENT_TOKEN: ${HATCHET_CLIENT_TOKEN}
      HATCHET_CLIENT_TLS_STRATEGY: none
      DATABASE_URL: /data/remoodle.db
    volumes:
      - data:/data

volumes:
  data:
