export enum RouteName {
  Home = "home",
  Dashboard = "dashboard",
  Courses = "courses",
  Login = "login",
  SignUp = "sign-up",
  Token = "token",
  NotFound = "404",
  Account = "account",
  AccountProfile = "profile",
  AccountNotifications = "notifications",
  File = "file",
  Course = "course",
  Grades = "course-grades",
  Assignment = "assignment",
  Terms = "terms",
  Privacy = "privacy",
}
