name: CI

on:
  push:
    branches: ["trunk"]
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  build:
    name: Test, Lint, and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 24.8.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

      - name: Format
        run: pnpm format

      - name: Test
        run: pnpm test
