name: "Release, please"

on:
  push:
    branches: [trunk]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Sync package.json version with tags
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v3
      - name: Run release-please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          monorepo-tags: true
          package-name: remoodle/web
          tag-separator: "-"
          pull-request-title-pattern: "chore${scope}: ${component} release (deploy-as: release-${version})"
  
  deploy:
    needs: release
    if: needs.release.outputs.deploy == 'true'
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Get shorten commit SHA
        id: short-sha
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: return context.sha.slice(0, 8);

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        env:
          COMMIT_SHA: ${{ github.sha }}
          CDN_HOST: ${{ vars.CDN_HOST }}
          CDN_PREFIX: ${{ steps.short-sha.outputs.result }}
        run: pnpm build-only

      - name: Deploy bundle on CDN with prefix
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy dist --project-name=remoodle --branch=${{ steps.short-sha.outputs.result }}

      - name: Deploy on production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy dist --project-name=remoodle --branch="production"
