name: "[backend] Publish Docker image"

on:
  push:
    branches:
      - "trunk"
      - "aitu-hack"
    paths:
      - "apps/backend/**"
    tags:
      - "remoodle/backend-*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to ghcr
        uses: docker/login-action@ba754150c9dbbaa912ae0ac3cfba43f84195cef2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_TOKEN }}

      - name: Build image
        run: |
          IMAGE_ID=ghcr.io/remoodle/backend
          GITHUB_REF="${{ github.ref }}"
          IMAGE_TAG=${GITHUB_REF#"refs/tags/remoodle/backend-v"}

          IMAGE_TAG=$(echo $IMAGE_TAG | sed -e 's/[\/-]/_/g')

          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)
          VERSION_TAG="${IMAGE_TAG}.${SHORT_SHA}"

          echo IMAGE_ID=$IMAGE_ID
          echo GITHUB_REF=$GITHUB_REF
          echo IMAGE_TAG=$IMAGE_TAG

          docker pull $IMAGE_ID:latest
          docker build . --file apps/backend/Dockerfile --tag $IMAGE_ID:$IMAGE_TAG --cache-from $IMAGE_ID:latest --build-arg VERSION_TAG=$VERSION_TAG
          docker build . --file apps/backend/Dockerfile --tag $IMAGE_ID:latest --cache-from $IMAGE_ID:$IMAGE_TAG --build-arg VERSION_TAG=$VERSION_TAG

          docker push $IMAGE_ID:$IMAGE_TAG
          docker push $IMAGE_ID:latest
