name: "[remoodle/frontend/web] Deploy on Stage/Production and Release"

on:
  push:
    branches: [trunk]
    paths:
      - "remoodle/frontend/web/**"
      - ".github/workflows/remoodle-frontend-web-release.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    name: Update Release PR, Build and Deploy to Stage / Production
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ROBOT_TOKEN }}
          release-type: node
          path: remoodle/frontend/web
          monorepo-tags: true
          package-name: remoodle/web
          tag-separator: "-"
          pull-request-title-pattern: "chore${scope}: ${component} release (deploy-as: release-${version})"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Get shorten commit SHA
        id: short-sha
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            return context.sha.slice(0, 8);

      - name: Install dependencies
        run: |
          cd tradelink/frontend
          yarn install --frozen-lockfile

      - name: Build and deploy bundle on CDN with prefix
        uses: ./.github/actions/wrangler-action
        env:
          COMMIT_SHA: ${{ github.sha }}
          CDN_HOST: ${{ vars.CDN_HOST }}
          CDN_PREFIX: ${{ steps.short-sha.outputs.result }}
        with:
          workingDirectory: ./remoodle/frontend/web
          preCommands: yarn build
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: >
            pages deploy dist --project-name=remoodle --branch=${{ steps.short-sha.outputs.result }}

      - name: Deploy on trunk
        uses: ./.github/actions/wrangler-action
        with:
          workingDirectory: ./remoodle/frontend/web
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: >
            pages deploy dist --project-name=remoodle --branch="trunk"

      - name: Deploy on production
        if: steps.release.outputs.releases_created == 'true'
        uses: ./.github/actions/wrangler-action
        with:
          workingDirectory: ./remoodle/frontend/web
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: >
            pages deploy dist --project-name=remoodle --branch="production"
