name: "[remoodle/frontend/web] Preview deployment"

on:
  pull_request:
    branches: [trunk]
    paths:
      - "remoodle/frontend/web/**"
      - ".github/workflows/remoodle-frontend-web-deploy-preview.yml"
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    working-directory: ./remoodle/frontend/web

jobs:
  deploy:
    name: Build and Deploy PR Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "remoodle/frontend/web/pnpm-lock.yaml"

      - name: Retrieve deploy-as info
        id: deploy-as
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            const pr = context.payload.pull_request.title;
            const branch = context.payload.pull_request.head.ref;

            const optionMatches = /\(deploy-as: (.*?)\)/.exec(pr);

            return optionMatches ? optionMatches[1] : branch;

      - name: Comment Deploy In Progress
        id: in-progress-comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueNumber = context.issue.number;
            const comments = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });

            const commentBody = "## Deploying on Cloudflare Pages\n\n" + ":hourglass: Deployment in progress...";

            const inProgressComment = comments.data.find((comment) => comment.body.includes("Deploying on Cloudflare Pages"));
            if (inProgressComment) {
              await github.issues.updateComment({
                issue_number: issueNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: inProgressComment.id,
                body: commentBody,
              });
              return inProgressComment.id;
            }

            const comment = await github.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            });
            return comment.data.id;

      - name: Get shorten commit SHA
        id: short-sha
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: return context.sha.slice(0, 8);

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        env:
          COMMIT_SHA: ${{ github.sha }}
          CDN_HOST: ${{ vars.CDN_HOST }}
          CDN_PREFIX: ${{ steps.short-sha.outputs.result }}
        run: pnpm build-only

      - name: Deploy bundle on CDN with prefix
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: ./remoodle/frontend/web
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy dist --project-name=remoodle --branch=${{ steps.short-sha.outputs.result }}

      - name: Deploy on named branch
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: ./remoodle/frontend/web
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy dist --project-name=remoodle --branch=${{ steps.deploy-as.outputs.result }}

      - name: Comment Deploy Failure
        if: failure()
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commitCommentId = ${{ steps.in-progress-comment.outputs.result }};

            await github.issues.updateComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commitCommentId,
              body: "## Deploying on Cloudflare Pages\n\n" + `:x: The deployment failed.`,
            });

      - name: Comment Deploy Preview Link
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commitCommentId = "${{ steps.in-progress-comment.outputs.result }}";
            const branch = "${{ steps.deploy-as.outputs.result }}";

            const cdnHost = "${{ vars.CDN_HOST }}";

            const subdomain = branch.replace(/\//g, '-').replace(/\./g, '-').toLowerCase().slice(0, 28);

            const previewURL = `https://${subdomain}.${cdnHost}`;

            await github.issues.updateComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commitCommentId,
              body: "## Deploying on Cloudflare Pages\n\n" + `:rocket: The PR preview for *${subdomain}* is ready and deployed at ${previewURL}`,
            });
